- hosts: all

  tasks:
    - name: Create prod config
      ansible.builtin.template:
        src: files/prod.conf.j2
        dest: "~/task_manager.prod.conf"

    - name: Run application
      docker_container:
        name: "task_manager"
        image: "strilkov/task_manager:{{ lookup('ansible.builtin.file', '../app/VERSION') }}"
        restart_policy: always
        recreate: yes
        env:
          TZ: "Europe/Kyiv"
          PROD_CONF: "/app/prod.conf"
        volumes:
          - "~/task_manager.prod.conf:/app/prod.conf:ro"
